apiVersion: sagemaker.amazonaws.com/v1
kind: HyperPodPyTorchJob
metadata:
  name: qwen-hpto
  labels:
    app.kubernetes.io/name: HyperPod
    app.kubernetes.io/managed-by: kustomize
spec:
  nprocPerNode: '1'
  runPolicy:
    jobMaxRetryCount: 2
    restartPolicy:
      numRestartBeforeFullJobRestart: 2
      evalPeriodSeconds: 21600
      maxFullJobRestarts: 1
    cleanPodPolicy: All
    logMonitoringConfiguration:
      - name: JobStart
        logPattern: ".*'loss':.*"
        expectedStartCutOffInSeconds: 600
      - name: JobHangingDetection
        logPattern: ".*'loss':.*"
        expectedRecurringFrequencyInSeconds: 600
  replicaSpecs:
    - name: pods
      replicas: 1
      template:
        metadata:
          labels:
            job-name: qwen-sft-hpto
            replica-type: pods
        spec:
          serviceAccountName: sagemaker-mlflow-sa
          volumes:
            - name: shmem
              hostPath:
                path: /dev/shm
            - name: local
              hostPath:
                path: /mnt/k8s-disks/0
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: fsx-claim
            - name: code-sync
              emptyDir: {}
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      job-name: qwen-sft-hpto
                  topologyKey: kubernetes.io/hostname
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.kubernetes.io/instance-type
                        operator: In
                        values:
                          - "ml.g5.2xlarge"
          containers:
            - name: pytorch
              image: public.ecr.aws/o8u4p8i7/qwen-hpto:latest
              imagePullPolicy: Always
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              env:
                - name: LOGLEVEL
                  value: INFO
                - name: TORCH_DISTRIBUTED_DEBUG
                  value: DETAIL
                - name: TORCH_NCCL_ENABLE_MONITORING
                  value: '1'
                - name: TORCH_NCCL_TRACE_BUFFER_SIZE
                  value: '20000'
                - name: TORCH_NCCL_DUMP_ON_TIMEOUT
                  value: '1'
                - name: TORCH_NCCL_DEBUG_INFO_TEMP_FILE
                  value: /local/nccl_trace_rank_
                - name: PYTORCH_CUDA_ALLOC_CONF
                  value: 'expandable_segments:True'
                - name: NCCL_DEBUG
                  value: INFO
                - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
                  value: '1'
              command: ["hyperpodrun"]
              args:
                - "--tee=3"
                - "--shutdown-timeout=120"
                - "--nnodes=1"
                - "--nproc_per_node=1"
                - /workspace/qwen_train.py
                - '--train_path=/workspace/train'
                - '--eval_path=/workspace/eval'
                - '--model_id=Qwen/Qwen3-1.7B'
                - '--max_seq_length=1024'
                - '--mlflow_tracking_server=arn:aws:sagemaker:us-west-2:535002850097:mlflow-tracking-server/SageMakerMLFlowTS'
                - '--mlflow_exp_name=qwen-sft'
                - '--mlflow_run_id=37579957ebe8446b9fbddcc9ed7665fd'
                - '--per_device_train_batch_size=2'
                - '--per_device_eval_batch_size=2'
                - '--gradient_accumulation_steps=4'
                - '--learning_rate=2e-4'
                - '--num_train_epochs=1'
                - '--logging_steps=10'
                - '--bf16=True'
                - '--save_strategy=steps'
                - '--eval_strategy=steps'
                - '--save_steps=400'
                - '--eval_steps=200'
                - '--eval_on_start=True'
                - '--max_steps=400'
                - '--output_dir=/data/checkpoint'
                - '--report_to=mlflow'
              volumeMounts:
                - name: shmem
                  mountPath: /dev/shm
                - name: local
                  mountPath: /local
                - name: persistent-storage
                  mountPath: /data
                - name: code-sync
                  mountPath: /code